language: java

jdk: oraclejdk8

sudo: required

services:
  - docker

env:
  - MVN_COMMAND="clean install -Dmaven.javadoc.skip=true -B -V"
  - MVN_COMMAND="verify -P integration"

script: "mvn $MVN_COMMAND"
