version: '2.1'

services:
    alice:
        build:
            context: .
        image: bisq-api
        ports:
          - 8080:8080
        volumes:
          - m2:/root/.m2
    bob:
        build:
            context: .
        image: bisq-api
        ports:
          - 8081:8080
        volumes:
          - m2:/root/.m2

volumes:
  m2:
    name: m2
